#!/bin/bash -ex
# TurnKey Linux - Ruby runtime via rbenv
#
# Installs rbenv + ruby-build and compiles the requested Ruby version
# with jemalloc support. Designed to be sourced by appliance conf.d/main
# scripts that need Ruby (Rails, Mastodon, Redmine, etc.)
#
# Usage in appliance conf.d/main:
#   RUBY_VERSION=3.4.7
#   source /turnkey/fab/common/conf/ruby
#
# The calling script MUST set RUBY_VERSION before sourcing this file.
# If not set, falls back to the version in RUBY_DEFAULT_VERSION.
#
# [Marcos Méndez @ POPSOLUTIONS <https://github.com/marcos-mendez>]

RBENV_ROOT=/usr/local/rbenv
RUBY_DEFAULT_VERSION=3.3.6

if [ -z "$RUBY_VERSION" ]; then
    echo "Warning: RUBY_VERSION not set, using default: $RUBY_DEFAULT_VERSION"
    RUBY_VERSION=$RUBY_DEFAULT_VERSION
fi

[ "$FAB_HTTP_PROXY" ] && export http_proxy=$FAB_HTTP_PROXY

if [ ! -d "$RBENV_ROOT" ]; then
    git clone https://github.com/rbenv/rbenv.git $RBENV_ROOT --depth=1
fi

if [ ! -d "$RBENV_ROOT/plugins/ruby-build" ]; then
    git clone https://github.com/rbenv/ruby-build.git $RBENV_ROOT/plugins/ruby-build --depth=1
fi

$RBENV_ROOT/plugins/ruby-build/install.sh

if [ ! -f /root/.bashrc.d/rbenv ]; then
    mkdir -p /root/.bashrc.d
    cat << 'EOF' > /root/.bashrc.d/rbenv
export RBENV_ROOT=/usr/local/rbenv
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init -)"
EOF
    chmod +x /root/.bashrc.d/rbenv
fi

export RBENV_ROOT
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init -)"

mkdir -p $RBENV_ROOT/rbenv.d/rehash

cat << 'EOF' > $RBENV_ROOT/rbenv.d/rehash/gem-symlinks.bash
#!/bin/bash
SHIM_PATH='/usr/local/rbenv/shims'
for shim in ${SHIM_PATH}/*; do
    ln -sf "${shim}" "/usr/local/bin/$( basename ${shim} )"
done
EOF
chmod +x $RBENV_ROOT/rbenv.d/rehash/gem-symlinks.bash

MAKE_OPTS="-j$(nproc)" \
    RUBY_CONFIGURE_OPTS="--with-jemalloc --disable-install-doc" \
    rbenv install $RUBY_VERSION

rbenv global $RUBY_VERSION

gem update --system
gem install --no-document bundler
